seed: 1337
device: cpu
experiment_name: seg_demo

train:
  epochs: 2
  task: segmentation
  log_interval: 2
  save_interval: 1
  plot: true

logging:
  enabled: true
  level: INFO
  log_file: exp.log

data:
  name: voc_segmentation
  root: /data/datasets
  batch_size: 32
  # kwargs is passed to your instance of BaseDataset, define as you like
  kwargs:
    val_split: 0.1  # default 0.2
    random_state: 42

model:
  - name: unet
    # name: complex_low_rank_model
    pretrained: false
    pretrained_path: null  # only fill if pretrained is true
    kwargs:
      null
      

optim:
  name: adam
  lr: 3.e-4
  kwargs:  # fill w.r.t. chosen optimizer
    # betas: [0.9, 0.999]
    # eps: 1e-08
    weight_decay: 1.e-5
  scheduler:
    # name: exponential_lr
    # kwargs: 
    #   gamma: 0.5

# for predefined losses, see: /losses/build.py
losses:
  - name: ce
    weight: 1.0
  # - name: focal_loss
  #   weight: 0.2

metrics:
  - name: accuracy
  - name: precision
    kwargs:
      average: weighted
  - name: recall
    kwargs:
      average: weighted
  - name: f1
    kwargs:
      average: weighted

tracker:
  enabled: false
  name: mlflow
  port: 5000
  kwargs:
    mlflow_arg: 1
